baseURL = 'https://khushiramsingh680.github.io/ocp/'
languageCode = 'en-us'
title = 'Openshift Documentation'
theme = 'relearn'
relativeURLs = true
canonifyURLs = true

[params]
  # Relearn theme-specific parameters
  colorTheme = "light"
  layout = "wide"



